config/routes.rb
Meth::Application.routes.draw do
  resources :lines
  get 'test' => 'welcome#test'
  get 'env' => 'welcome#env'

  resources :nested_hints

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages do
    get 'fullscreen'
    get 'properties_all'
    resources :slides do 
      resources :lines
      resources :hints
    end
    resources :properties
  end
  resources :hints

  root :to => 'welcome#welcome2d'

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  attr_accessible :page_id, :image, :hints_attributes, :id
  attr_accessor :accessible
  has_attached_file :image, styles: { thumb: "100x100#", large: "600x300>" } #, path: "/images/#{page_id}/"

  has_many :hints, dependent: :destroy
  accepts_nested_attributes_for :hints, allow_destroy: true
  has_many :lines

  belongs_to :page


end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  # GET /page/slides
  # GET /page/slides.json
  def index
    @page_slides = Slide.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page_slides }
    end
  end

  # GET /page/slides/1
  # GET /page/slides/1.json
  def show
    @page_slide = Slide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page_slide }
    end
  end

  # GET /page/slides/new
  # GET /page/slides/new.json
  def new
    @page_slide = Slide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page_slide }
    end
  end

  # GET /page/slides/1/edit
  def edit
    @page_slide = Slide.find(params[:id])
    @fullscreen = params[:fullscreen].try(:to_bool) || false
  end

  # POST /page/slides
  # POST /page/slides.json
  def create
    @page_slide = Slide.new(params[:page_slide])

    respond_to do |format|
      if @page_slide.save
        format.html { redirect_to @page_slide, notice: 'Slide was successfully created.' }
        format.json { render json: @page_slide, status: :created, location: @page_slide }
      else
        format.html { render action: "new" }
        format.json { render json: @page_slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /page/slides/1
  # PUT /page/slides/1.json
  def update
    @page_slide = Slide.find(params[:id])

    respond_to do |format|
      if @page_slide.update_attributes(params[:page_slide])
        format.html { redirect_to page_slide_url(@page_slide.page, @page_slide), notice: 'Slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page_slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page/slides/1
  # DELETE /page/slides/1.json
  def destroy
    @page_slide = Slide.find(params[:id])
    @page_slide.destroy

    respond_to do |format|
      format.html { redirect_to page_slides_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/page/slides_helper.rb
module Page::SlidesHelper
end

app/views/slides/_form.html.slim
.xz#xz style="margin-top: 10px"
  .btn-group
    = link_to  new_page_slide_hint_path(@page_slide.page, @page_slide, Hint.new, fullscreen: @fullscreen) , remote: true, class: 'btn btn-info ' do
      i.icon-plus

  |&nbsp;
  .btn-group
    = link_to  new_page_slide_line_path(@page_slide.page, @page_slide, Line.new, type: 'line_top', fullscreen: @fullscreen) , remote: true, class: 'btn btn-inverse ' do
      |&#8722;
    = link_to  new_page_slide_line_path(@page_slide.page, @page_slide, Line.new, type: 'line_top_right', fullscreen: @fullscreen) , remote: true, class: 'btn btn-inverse ' do
      img src='/assets/top_right.gif'
    = link_to  new_page_slide_line_path(@page_slide.page, @page_slide, Line.new, type: 'line_top_left', fullscreen: @fullscreen) , remote: true, class: 'btn btn-inverse ' do
      img src='/assets/top_left.gif'

    = link_to  new_page_slide_line_path(@page_slide.page, @page_slide, Line.new, type: 'line_bottom_left', fullscreen: @fullscreen) , remote: true, class: 'btn btn-inverse ' do
      img src='/assets/bottom_left.gif'
    = link_to  new_page_slide_line_path(@page_slide.page, @page_slide, Line.new, type: 'line_bottom_right', fullscreen: @fullscreen) , remote: true, class: 'btn btn-inverse ' do
      img src='/assets/bottom_right.gif'
  br
  br
  / #dragable_plane
  .pull-center
    #nested_form style="position:relative; top: -40px; height: 500px; width: 900px; margin: auto; background-size: cover; background-image: url('#{@page_slide.image}');"

      / == render partial: 'hint_fields', collection: @page_slide.hints
      == render partial: 'hints/hint_on_edit', collection: @page_slide.hints
      == render partial: 'lines/line_fields',  collection: @page_slide.lines
  br
  br
  br

app/views/slides/_hint_fields.html.slim
div class="fields drago hint_#{hint_fields.id} hint" style="position: absolute; left: #{current_ord_x(hint_fields, @fullscreen)}; top: #{current_ord_y(hint_fields, @fullscreen)};" id="field_#{hint_fields.id}"
  = simple_form_for (hint_fields), remote: true, id: hint_fields.id, format: :js, html: { :'data-type' => 'script' } do |f|
    / = f.error_notification

    = f.input :title, label: false, placeholder: 'Заголовок'
    = f.input :slide_id, as: :hidden, input_html: { value: @page_slide.id }
    = f.input :_destroy, as: :hidden
    = f.input :x, as: :hidden, input_html: { class: 'x_ord' }
    = f.input :y, as: :hidden, input_html: { class: 'y_ord' }
    .pull-left
      = link_to '+', new_nested_hint_path(hint_id: hint_fields.id), class: 'btn btn-mini btn-inverse', remote: true
    div.pull-right
      .btn-group
        - if hint_fields.new_record?
          = f.submit "Закрепить", class: 'btn btn-warning btn-mini', remote: true
        - else
          = link_to 'Редактировать', edit_hint_path(hint_fields), class: 'btn btn-info btn-mini'
          = f.submit "Сохранить", class: 'btn btn-success btn-mini'
        / = link_to_remove_fields "X", f 
        = link_to  hint_path(hint_fields), method: :delete, remote: true, class: 'btn btn-mini btn-danger' do
          |&#8855;
== render partial: 'nested_hints/nested_hint_fields', collection: hint_fields.nested_hints






/ div class="fields drago"

/   = f.input :x, as: :hidden, input_html: { class: 'x_ord'}
/   = f.input :y, as: :hidden, input_html: { class: 'y_ord'}
/   = f.input :title, label: false, placeholder: 'Заголовок',input_html: { class: 'y_ord'}
/   = f.input :slide_id, as: :hidden
/   / = f.input :content, as: :ckeditor
/   = f.input :_destroy, as: :hidden
/   = link_to_remove_fields "- Удалить подсказку", f 

/ / name: "#{f.object_name.gsub!(/_attributes/, '')}[x]", id: f.object_name.gsub!(/_attributes/, ''),value: 0 
/ / name: f.object_name.gsub!(/_attributes/, ''), id: f.object_name.gsub!(/_attributes/, ''), value: 0

/ / , name: f.object_name.gsub!(/_attributes/, ''), id: f.object_name.gsub!(/_attributes/, '') 

app/views/slides/_slide.html.slim
.span2 style="margin-bottom: 20px !important;"
	= image_tag slide.image, width: 100, height: 100 
	br
	= link_to "Редактировать", edit_page_slide_path(slide.page, slide), class: 'btn btn-mini btn-inverse'

app/views/slides/_slide_in_block.html.slim
div class="item" style="background-size: cover; background-image: url('#{slide_in_block.image}'); width: 350px; height: 250px"

app/views/slides/edit.html.slim
coffee:
  $(document).ready ->
    if getURLParameter('fullscreen') == "true"
      screenfull.toggle( $('#container')[0])



.well style="width: 100% !important; height: 100% !important; position: fixed; top: 59px; left: 0; display: block; overflow-y: scroll"
  .inline
    = link_to edit_page_path(@page_slide.page), class: 'btn btn-inverse' do
      i.icon-arrow-left&nbsp;
      |Назад
    .pull-right
      / = link_to 'Смена режима отображения', url_for(fullscreen: !@fullscreen), class: 'btn btn-inverse', id: 'toggle'
  == render 'form'

  
br
br


- if params[:fullscreen]
  coffee:
    $(document).ready ->
      $('div.drago').draggable
        drag: ->
          $(this).find('.x_full').val($(this).css('left'))
          $(this).find('.y_full').val($(this).css('top'))
        
      $('.nested_hint')
        .draggable
          drag: ->
            $(this).find('.x_full').val($(this).css('left'))
            $(this).find('.y_full').val($(this).css('top'))
        .resizable
          handles: "se, sw",
          resize: ->
            $(this).find('.width_ord').val($(this).css('width'))
            $(this).find('.height_ord').val($(this).css('height'))


      $('.line')
        .draggable
          drag: ->
            $(this).find('.x_full').val($(this).css('left'))
            $(this).find('.y_full').val($(this).css('top'))
        .resizable
          handles: "se, sw",
          resize: ->
            $(this).find('.width_ord').val($(this).css('width'))
            $(this).find('.height_ord').val($(this).css('height'))
      $(document).ready ->
        $('.hint')
          .draggable
            drag: ->
              $(this).find('.x_full').val($(this).css('left'))
              $(this).find('.y_full').val($(this).css('top'))
              $(this).find('.btn-success').removeClass('btn-success').stop().addClass('btn-warning')
          .resizable
            resize: ->
              $(this).find('.width_ord').val($(this).css('width'))
              $(this).find('.height_ord').val($(this).css('height'))
              $(this).find('.btn-success').removeClass('btn-success').stop().addClass('btn-warning')

-else 
  coffee:
    $(document).ready ->

      $('div.drago').draggable
        drag: ->
          $(this).find('.x_ord').val($(this).css('left'))
          $(this).find('.y_ord').val($(this).css('top'))
        
      $('.nested_hint')
        .draggable
          drag: ->
            $(this).find('.x_ord').val($(this).css('left'))
            $(this).find('.y_ord').val($(this).css('top'))
        .resizable
          handles: "se, sw",
          resize: ->
            $(this).find('.width_ord').val($(this).css('width'))
            $(this).find('.height_ord').val($(this).css('height'))


      $('.line')
        .draggable
          drag: ->
            $(this).find('.x_ord').val($(this).css('left'))
            $(this).find('.y_ord').val($(this).css('top'))
        .resizable
          handles: "se, sw",
          resize: ->
            $(this).find('.width_ord').val($(this).css('width'))
            $(this).find('.height_ord').val($(this).css('height'))
        $('.hint')
          .draggable
            drag: ->
              $(this).find('.x_ord').val($(this).css('left'))
              $(this).find('.y_ord').val($(this).css('top'))
              $(this).find('.btn-success').removeClass('btn-success').stop().addClass('btn-warning')
          .resizable
            resize: ->
              $(this).find('.width_ord').val($(this).css('width'))
              $(this).find('.height_ord').val($(this).css('height'))
              $(this).find('.btn-success').removeClass('btn-success').stop().addClass('btn-warning')

app/views/slides/index.html.slim
h1 Listing page_slides

table
  tr
    th
    th
    th

  - @page_slides.each do |page_slide|
    tr
      td = link_to 'Show', page_slide
      td = link_to 'Edit', edit_page_slide_path(page_slide)
      td = link_to 'Destroy', page_slide, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Slide', new_page_slide_path

app/views/slides/new.html.slim
h1 New page_slide

== render 'form'

= link_to 'Back', page_slides_path

app/views/slides/show.html.slim
p#notice = notice


= link_to 'Edit', edit_page_slide_path(@page_slide.page, @page_slide)
'|
= link_to 'Back', page_slides_path