config/routes.rb
Meth::Application.routes.draw do
  resources :lines
  get 'test' => 'welcome#test'
  get 'env' => 'welcome#env'

  resources :nested_hints

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages do
    get 'fullscreen'
    get 'properties_all'
    resources :slides do 
      resources :lines
      resources :hints
    end
    resources :properties
  end
  resources :hints

  root :to => 'welcome#welcome2d'

end

app/models/hint.rb
class Hint < ActiveRecord::Base
  attr_accessible :content, :title, :x, :y, :slide_id, :id, :width, :height, :x_full, :y_full
  belongs_to :slide
  has_many :nested_hints
end


class Triangle
  attr :a, :b
  
  def place
    (a * b) / 2
  end
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  respond_to :js, :html
  # GET /hints
  # GET /hints.json
  def index
    @hints = Hint.all

  end

  # GET /hints/1
  # GET /hints/1.json
  def show
    @hint = Hint.find(params[:id])

  end

  # GET /hints/new
  # GET /hints/new.json
  def new
    @hint = Hint.new
    @fullscreen = params[:fullscreen].try(:to_bool) || false
    @page_slide = Slide.find(params[:slide_id]) if params[:slide_id]
    render 'new'
  end

  # GET /hints/1/edit
  def edit
    @hint = Hint.find(params[:id])
  end

  # POST /hints
  # POST /hints.json
  def create
    @hint = Hint.new(params[:hint])

    @hint.save
  end

  # PUT /hints/1
  # PUT /hints/1.json
  def update
    @hint = Hint.find(params[:id])
    @hint.update_attributes(params[:hint])
  end

  # DELETE /hints/1
  # DELETE /hints/1.json
  def destroy
    @hint = Hint.find(params[:id])
    @hint.destroy
    # redirect_to hints_url 
  end
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/views/hints/_create.html.slim
/ = simple_form_for (@hint), remote: true, id: @hint.id, format: :js, html: { :'data-type' => 'script' } do |f|
/   / = f.error_notification

/   = f.input :title, label: false, placeholder: 'Заголовок'
/   = f.input :slide_id, as: :hidden
/   = f.input :_destroy, as: :hidden
/   = f.input :x, as: :hidden, input_html: { class: 'x_ord' }
/   = f.input :y, as: :hidden, input_html: { class: 'y_ord' }
/   .pull-left
/     = link_to '+', new_nested_hint_path(hint_id: @hint.id), class: 'btn btn-mini btn-inverse', remote: true
/   div.pull-right
/     .btn-group
/       - if @hint.new_record?
/         = f.submit "Закрепить", class: 'btn btn-warning btn-mini', remote: true
/       - else
/         = link_to 'Редактировать', edit_hint_path(@hint), class: 'btn btn-info btn-mini'
/         = f.submit "Сохранить", class: 'btn btn-success btn-mini'
/       / = link_to_remove_fields "X", f 
/       = link_to "X", hint_path(@hint), method: :delete, remote: true, class: 'btn btn-mini btn-danger'
.title
  .pull-left
    h3 = @hint.title.upcase
  .pull-right
    = simple_form_for (@hint), remote: true, id: @hint.id, format: :js, html: { :'data-type' => 'script'} do |f|
      / = f.error_notification
      = f.input :height, as: :hidden, input_html: { class: 'height_ord' }
      = f.input :width, as: :hidden, input_html: { class: 'width_ord' }
      = f.input :x, as: :hidden, input_html: { class: 'x_ord' }
      = f.input :y, as: :hidden, input_html: { class: 'y_ord' }
      = f.input :x_full, as: :hidden, input_html: { class: 'x_full' }
      = f.input :y_full, as: :hidden, input_html: { class: 'y_full' }
      = f.input :_destroy, as: :hidden
      div.pull-right
        .btn-group style="position: absolute; top: 0; right: 0;"
          = link_to '+', new_nested_hint_path(hint_id: @hint.id), class: 'btn btn-mini btn-inverse', remote: true

          - if @hint.new_record?
            = link_to_submit class: 'btn btn-warning btn-mini', remote: true do
              i.icon-ok
          - else
            = link_to_submit  class: 'btn btn-success btn-mini' do
              i.icon-ok
              / = link_to_remove_fields "X", f 
          = link_to edit_hint_path(@hint), class: 'btn btn-success btn-mini show_modal', remote: true do
            i.icon-pencil
          = link_to "X", "/hints/#{@hint.id}", method: :delete, remote: true, class: 'btn btn-mini btn-danger'

div class="content"
  = raw @hint.content

app/views/hints/_edit.html.slim
/ .modal-header
/   button.close data-dismiss="modal" aria-hidden="true"x
/   h3#oneModalLabel Редактировать подсказку
= simple_form_for (@hint), remote: true do |f|
  = f.error_notification
  = f.input :title, label: false, placeholder: 'Заголовок'
  = f.input :content, as: :ckeditor, label: 'Описание'
  = f.input :slide_id, as: :hidden
  = f.input :x_full, as: :hidden, input_html: { class: 'x_full' }
  = f.input :y_full, as: :hidden, input_html: { class: 'y_full' }
  = f.input :x, as: :hidden, input_html: { class: 'x_ord' }
  = f.input :y, as: :hidden, input_html: { class: 'y_ord' }
  .modal-footer
    = f.submit "Сохранить", class: 'btn btn-success'

app/views/hints/_form.html.slim
div class="fields drago field_new_hint" style="position: absolute"
  = simple_form_for (@hint), remote: true, id: @hint.id, format: :js, html: { :'data-type' => 'script' } do |f|
    / = f.error_notification

    = f.input :title, label: false, placeholder: 'Заголовок'
    = f.input :height, as: :hidden, input_html: { class: 'height_ord' }
    = f.input :width, as: :hidden, input_html: { class: 'width_ord' }
    = f.input :x, as: :hidden, input_html: { class: 'x_ord' }
    = f.input :y, as: :hidden, input_html: { class: 'y_ord' }
    = f.input :x_full, as: :hidden, input_html: { class: 'x_full' }
    = f.input :y_full, as: :hidden, input_html: { class: 'y_full' }
    = f.input :slide_id, as: :hidden, input_html: { value: @page_slide.id  }
    = f.input :_destroy, as: :hidden
    div.pull-right
      .btn-group
        - if @hint.new_record?
          = f.submit "Закрепить", class: 'btn btn-warning btn-mini', remote: true
        - else
          = f.submit "Закреплено", class: 'btn btn-success btn-mini'
        / = link_to_remove_fields "X", f 
        = link_to_function "X", "javascript:$(this).closest('.field_new_hint').hide()", method: :delete, remote: true, class: 'btn btn-mini btn-danger'

app/views/hints/_hint_on_edit.html.slim
div class="hint disable-select" style="position: absolute; left: #{current_ord_x(hint_on_edit, @fullscreen)}; top: #{current_ord_y(hint_on_edit, @fullscreen)};  z-index: 1000; width: #{hint_on_edit.width}; height: #{hint_on_edit.height} "   id="hint_#{ hint_on_edit.id }"
  .title
    .pull-left
      h3 = hint_on_edit.title.upcase
    .pull-right
      = simple_form_for (hint_on_edit), remote: true, id: hint_on_edit.id, format: :js, html: { :'data-type' => 'script'} do |f|
        / = f.error_notification

        = f.input :x, as: :hidden, input_html: { class: 'x_ord' }
        = f.input :y, as: :hidden, input_html: { class: 'y_ord' }
        = f.input :x_full, as: :hidden, input_html: { class: 'x_full' }
        = f.input :y_full, as: :hidden, input_html: { class: 'y_full' }
        = f.input :height, as: :hidden, input_html: { class: 'height_ord' }
        = f.input :width, as: :hidden, input_html: { class: 'width_ord' }
        = f.input :_destroy, as: :hidden
        div.pull-right
          .btn-group style="position: absolute; top: 0; right: 0"
            = link_to '+', new_nested_hint_path(hint_id: hint_on_edit.id), class: 'btn btn-mini btn-inverse', remote: true

            - if hint_on_edit.new_record?
              = link_to_submit class: 'btn btn-warning btn-mini', remote: true do
                i.icon-ok
            - else
              = link_to_submit  class: 'btn btn-success btn-mini' do
                i.icon-ok
                / = link_to_remove_fields "X", f 
            = link_to edit_hint_path(hint_on_edit), class: 'btn btn-success btn-mini show_modal', remote: true do
              i.icon-pencil
            = link_to "X", "/hints/#{hint_on_edit.id}", method: :delete, remote: true, class: 'btn btn-mini btn-danger'

  div class="content"
    = raw hint_on_edit.content



== render partial: 'nested_hints/nested_hint_fields', collection: hint_on_edit.nested_hints

app/views/hints/edit.html.slim
/ .modal-header
/   button.close data-dismiss="modal" aria-hidden="true"x
/   h3#oneModalLabel Редактировать подсказку
.modal-body
  = simple_form_for (@hint) do |f|
  = f.error_notification
  = f.input :title, label: false, placeholder: 'Заголовок'
  = f.input :content, as: :ckeditor, label: 'Описание'
  = f.input :slide_id, as: :hidden
  = f.input :x, as: :hidden, input_html: { class: 'x_ord' }
  = f.input :y, as: :hidden, input_html: { class: 'y_ord' }
.modal-footer
  = f.submit "Сохранить", class: 'btn btn-success'

app/views/hints/index.html.slim
h1 Listing hints

table
  tr
    th
    th
    th

  - @hints.each do |hint|
    tr
      td = link_to 'Show', hint
      td = link_to 'Edit', edit_hint_path(hint)
      td = link_to 'Destroy', hint, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Hint', new_hint_path

app/views/hints/new.html.slim
h1 New hint

== render 'form'

= link_to 'Back', hints_path

app/views/hints/show.html.slim
p#notice = notice


= link_to 'Редактировать', edit_hint_path(@hint)
'|
= link_to 'Назад', edit_page_slide_path(@hint.slide.page, @hint.slide)