config/routes.rb
Meth::Application.routes.draw do
  resources :lines
  get 'test' => 'welcome#test'
  get 'env' => 'welcome#env'

  resources :nested_hints

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages do
    get 'fullscreen'
    get 'properties_all'
    resources :slides do 
      resources :lines
      resources :hints
    end
    resources :properties
  end
  resources :hints

  root :to => 'welcome#welcome2d'

end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :content, :page_id, :title
  belongs_to :pages
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @page = Page.find(params[:page_id])

    @property = @page.property.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
    @page = Page.find(params[:page_id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @page = Page.find(params[:page_id])
    @property = @page.property.build(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to edit_page_path @page, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])
    @page = Page.find(params[:page_id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to edit_page_path @page, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.slim
= simple_form_for [@page, @property] do |f|
  = f.error_notification

  .form-inputs
  	= f.input :title
  	= f.input :content, as: :ckeditor

  .form-actions
    = f.button :submit

app/views/properties/_property.html.slim
tr
	td= property.title
	td= link_to property.title, edit_page_property_path(@page, property)
	td= link_to 'Удалить', page_property_path(@page, property), :confirm => 'Are you sure?', :method => :delete

app/views/properties/_property_in_page.html.slim
div class="shortcode-toggle toggle-Toggle1 closed"
	h4 class="toggle-trigger"
		a class="hide_me" href="#"=property_in_page.title
	div class="toggle-content"
		= raw property_in_page.content

app/views/properties/edit.html.slim
.well
	h1 Editing property

	== render 'form'

app/views/properties/index.html.slim
h1 Listing properties

table
  tr
    th
    th
    th

  - @properties.each do |property|
    tr
      td = link_to 'Show', property
      td = link_to 'Edit', edit_property_path(property)
      td = link_to 'Destroy', property, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Property', new_property_path

app/views/properties/new.html.slim
.well
	h1 New property

	== render 'form'

app/views/properties/show.html.slim
p#notice = notice


= link_to 'Edit', edit_property_path(@property)
'|
= link_to 'Back', properties_path