config/routes.rb
Meth::Application.routes.draw do
  resources :lines
  get 'test' => 'welcome#test'
  get 'env' => 'welcome#env'

  resources :nested_hints

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages do
    get 'fullscreen'
    get 'properties_all'
    resources :slides do 
      resources :lines
      resources :hints
    end
    resources :properties
  end
  resources :hints

  root :to => 'welcome#welcome2d'

end

app/views/pages/_display_hint.html.slim
div class="hint disable-select" style="position: absolute; left: #{current_ord_x(display_hint, @fullscreen)}; top: #{current_ord_y(display_hint, @fullscreen)};  z-index: 1000; width: #{display_hint.width}; height: #{display_hint.height};" 
  .title
    h3 = display_hint.title.upcase
  div class="content disable-select"
    = raw display_hint.content
== render display_hint.nested_hints

app/views/pages/_display_page_full.html.slim
/ .row
/   div class="span6 offset2 well"
/     div#main-block class="disable-select"
/       .title
/         h3 =@page.title
/       div class="content disable-select" id="content_pokaz"
/         == render 'pages/pages_property', page: @page
/         == render partial: 'properties/property_in_page', collection: @page.properties
/   div class="span4 offset2 well"
/     #img-block
/       div class='slides-block carousel' id="slider_full"
        
/         div class="carousel-inner"
/           / div class="item active" style="background-size: cover; background-image: url(#{@page.slide.url}); width: 350px; height: 250px"
/             / img src="#{@page.slide.url}"  height="100%"
/           - if @page.slides.present?  
/             - first_slide = @page.slides.shift
/             div class="item active" style="background-size: cover; background-image: url('#{first_slide.image}'); width: 350px; height: 250px"
/             == render partial: 'slides/slide_in_block', collection: @page.slides
/         ol class="carousel-indicators" style="bottom: 10px !important;"
/           - if @page.slides.size >= 1
/             li data-target="#slider_full" data-slide-to="0" class="active"
/             - 1.upto @page.slides.size do |slide|
/               li data-target="#slider_full" data-slide-to="#{slide}"
/         / a class="carousel-control left" href="#slider_full" data-slide="prev"&lsaquo;
/         / a class="carousel-control right" href="#slider_full" data-slide="next"&rsaquo;

/       .slide-links
/         ul style="margin-left: 10px"
/           li 
/             - if @page.city_agregation != nil && @page.city_agregation != 0
/               =link_to 'Город', '#', class: 'active'
/             - else
/               =link_to 'Город', '#'
/           li 
/             - if @page.region != nil && @page.region != 0
/               =link_to 'Округ', '#', class: 'active'
/             - else
/               =link_to 'Округ', '#'
/           li
/             - if @page.cust != nil && @page.cust != 0 
/               =link_to 'Куст', '#', class: 'active'
/             - else
/               =link_to 'Куст', '#'
/           li
/             - if @page.filial != nil && @page.filial != 0
/               =link_to 'Филиал', '#', class: 'active'
/             - else
/               =link_to 'Филиал', '#'


#main-content 
  #left_content
    div#main-block class="disable-select"
      .title
        h3 =@page.title
      div class="content disable-select" id="content_pokaz"
        == render 'pages/pages_property', page: @page
        == render partial: 'properties/property_in_page', collection: @page.properties
        .clearFix style="height: 50px"
        
  #right_content
    #img-block
      div class='slides-block carousel' id="slider_full"
        
        div class="carousel-inner"
          / div class="item active" style="background-size: cover; background-image: url(#{@page.slide.url}); width: 350px; height: 250px"
            / img src="#{@page.slide.url}"  height="100%"
          - if @page.slides.present?  
            - first_slide = @page.slides.shift
            div class="item active" style="background-size: cover; background-image: url('#{first_slide.image}'); width: 350px; height: 250px"
            == render partial: 'slides/slide_in_block', collection: @page.slides
        ol class="carousel-indicators" style="bottom: 10px !important;"
          - if @page.slides.size >= 1
            li data-target="#slider_full" data-slide-to="0" class="active"
            - 1.upto @page.slides.size do |slide|
              li data-target="#slider_full" data-slide-to="#{slide}"
        / a class="carousel-control left" href="#slider_full" data-slide="prev"&lsaquo;
        / a class="carousel-control right" href="#slider_full" data-slide="next"&rsaquo;

      .slide-links
        ul style="margin-left: 10px"
          li 
            - if @page.city_agregation != nil && @page.city_agregation != 0
              =link_to 'Город', '#', class: 'active'
            - else
              =link_to 'Город', '#'
          li 
            - if @page.region != nil && @page.region != 0
              =link_to 'Округ', '#', class: 'active'
            - else
              =link_to 'Округ', '#'
          li
            - if @page.cust != nil && @page.cust != 0 
              =link_to 'Куст', '#', class: 'active'
            - else
              =link_to 'Куст', '#'
          li
            - if @page.filial != nil && @page.filial != 0
              =link_to 'Филиал', '#', class: 'active'
            - else
              =link_to 'Филиал', '#'


    #menu-links
      / - if @children_pages.present?
      /   ul
      /     == render partial: 'shared/menu_links_slide', collection: @children_pages
      / - else
      /     p Нет связанных страниц
      / h3 style="color: white; padding: 0 0 0 10px; margin: 0;"Смежные показатели
      ul#mini-nav
        - @page.related_pages.uniq.each do |c|
          - next if c.to_i == 0
          li
            = link_to truncate(Page.find(c.to_i).title, length: 30), page_fullscreen_path(Page.find(c.to_i)), remote: true

app/views/pages/_display_slider_page.html.slim
.scrolled-container.viewport style="  overflow: inherit; test: test;"
    #slide_plane style="dislay: table-row"
      div class="carousel-inner disable-select" style="overflow: initial;"
        
        - @page.slides.each do |slide|
          div class="item #{'active' if @page.slides.index(slide) == 0}" style="position:relative; height: 500px !important; width: 900px !important; margin: auto; background-size: cover; background-image: url('#{slide.image}');"
            == render partial: 'display_hint', collection: slide.hints
            == render partial: 'lines/line', collection: slide.lines
      ol class="carousel-indicators"
        - if @page.slides.size >= 1
          - @page.slides.each do |num|
            li data-target="#slide_plane" data-slide-to="#{@page.slides.index(num)}" class="#{ 'active' if @page.slides.index(num) == 0}"

app/views/pages/_form.html.slim
br
br
.well
	- if @page.parent_id.present?
		= link_to 'Назад', edit_page_path(@page.parent), class: 'btn btn-inverse'
	- else
		= link_to 'Назад', pages_path, class: 'btn btn-inverse'
	br
	br
	= simple_form_for @page do |f|
		= f.input :parent_id, as: :hidden
		= f.input :title, placeholder: 'Краткое наименование', label: false
		/ = f.input :content, label: 'Контент', as: :ckeditor, input_html: { ckeditor: { toolbar: 'MyToolbar' } }
		= f.input :title_full_name, input_html: { value: 'Полное наименование' }, label: false
		= f.input :full_name, as: :ckeditor, label: false, input_html: { :ckeditor => { toolbar: 'Basic' } }
		br
		= f.input :semantic_load_title, label: false, input_html: { value: 'Смысловая нагрузка' }
		= f.input :semantic_load, as: :ckeditor, label: false
		br
		= f.input :measure_title, label: false, input_html: { value: 'Единица измерения' }
		= f.input :measure, as: :ckeditor, label: false
		br
		= f.input :count_update_title, label: false, input_html: { value: 'Период обновления' }
		= f.input :count_update, as: :ckeditor, label: false
		br
		= f.input :source_recived_title, label: false, input_html: { value: 'Источник получения' }
		= f.input :source_recived, as: :ckeditor, label: false
		br
		= f.input :analitic_cuts_title, label: false, input_html: { value: 'Аналитические разрезы' }
		= f.input :analitic_cuts, as: :ckeditor, label: false
		br
		= f.input :formula_title, label: false, input_html: { value: 'Формула' }
		= f.input :formula, as: :ckeditor, label: false
		br
		hr
		#nested_form
			= f.simple_fields_for :properties do |builder|
				== render 'property_fields', f: builder
		br
		= link_to_add_fields "Добавить новое свойство", f, :properties

		hr
		h3 Агрегация
		= f.input :city_agregation, as: :boolean, label: 'Город'
		= f.input :region, as: :boolean, label: 'Округ'
		= f.input :cust, as: :boolean,   label: 'Куст'
		= f.input :filial, as: :boolean, label: 'Филиал'
		br
		hr





		h3 Смежные показатели
		button type="button" class="btn btn-mini btn-success" data-toggle="collapse" data-target="#related_pages"
			|Показать/Скрыть
		br
		br
		#related_pages class="collapse"
			- @indicators.each do |related_page|
				- if @page.related_pages.include?(related_page.id.to_s)
					label.checkbox
						= check_box_tag "page[related_pages][]", related_page.id.to_s, checked: 'checked', class: 'check_boxes optional'
						= related_page.title
				- else
					label.checkbox
						= check_box_tag "page[related_pages][]", related_page.id.to_s, false, class: 'check_boxes optional'
						= related_page.title


		h3 Список изображений
		#nested_form_slide
			= f.simple_fields_for :slides do |slide|
				== render 'slide_fields', f: slide
		= link_to_add_fields_slide "Добавить изображение", f, :slides
	
		hr
		h3 Дополнительные свойства

		= f.input :show_in_menu, label: 'Отображать в главном меню?'
		= f.input :color, input_html: { class: 'color' }, label: 'Цвет подсветки слайда'
		= f.input :another_color, input_html: { class: 'color' }, label: 'Вторичный цвет подсветки'

		/ = f.input :slide, as: :file, label: 'Выберите файл слайда'
		br
		= f.submit 'Сохранить'

app/views/pages/_page.html.slim
tr
	td = page.title
	td	= link_to 'Редактировать', edit_page_path(page), class: 'btn btn-mini btn-inverse'
	td	= link_to 'Удалить', page, method: :delete, confirm: 'Вы уверены?', class: 'btn btn-danger btn-mini'

app/views/pages/_pages_property.html.slim
- if page.full_name.present?
	div class="shortcode-toggle toggle-Toggle1 open"
		h4 class="toggle-trigger"
			a class="hide_me" href="#"=page.title_full_name
		div class="toggle-content"
			= raw page.full_name.to_s
- if page.semantic_load.present?
	div class="shortcode-toggle toggle-Toggle1 open"
		h4 class="toggle-trigger"
			a class="hide_me" href="#"=page.semantic_load_title
		div class="toggle-content"
			= raw page.semantic_load.to_s
- if page.measure.present?
	div class="shortcode-toggle toggle-Toggle1 open"
		h4 class="toggle-trigger"
			a class="hide_me" href="#"=page.measure_title
		div class="toggle-content"
			= raw page.measure.to_s
- if page.count_update.present?
	div class="shortcode-toggle toggle-Toggle1 closed"
		h4 class="toggle-trigger"
			a class="hide_me" href="#"=page.count_update_title
		div class="toggle-content"
			= raw page.count_update
- if page.source_recived.present?
	div class="shortcode-toggle toggle-Toggle1 closed"
		h4 class="toggle-trigger"
			a class="hide_me" href="#"=page.source_recived_title
		div class="toggle-content"
			= raw page.source_recived.to_s
- if page.analitic_cuts.present?
	div class="shortcode-toggle toggle-Toggle1 closed"
		h4 class="toggle-trigger"
			a class="hide_me" href="#"=page.analitic_cuts_title
		div class="toggle-content"
			= raw page.analitic_cuts.to_s

- if page.formula.present?
	div class="shortcode-toggle toggle-Toggle1 closed"
		h4 class="toggle-trigger"
			a class="hide_me" href="#"=page.formula_title
		div class="toggle-content"
			= raw page.formula.to_s

app/views/pages/_property_for_page.html.slim
.fields
	= f.input :title, label: false, placeholder: 'Заголовок'
	= f.input :content, as: :ckeditor, label: false, :input_html => { :toolbar => 'Basic', :namespace => ""}
	= link_to_remove_fields "x", f 

app/views/pages/_slide_fields.html.slim
.fields
	.inline-block
		.pull-left
			- if f.object.present?
				= f.object.image_file_name
				|&nbsp;
			= f.file_field :image
		.pull-right
			= f.input :_destroy, as: :hidden
		= link_to_remove_fields "- Удалить изображение", f 
	br

app/views/pages/_visio_page_normative.html.slim
.container_normative

	.normative
		= link_to page_fullscreen_path(visio_page_normative), remote: true do 
			.slide_normative style="background: black; background-image: url('#{visio_page_normative.slides.first.image if visio_page_normative.slides.present?}');  background-size: cover; background-repeat: none;"
		.title
			.vert
				= link_to page_fullscreen_path(visio_page_normative), remote: true do 
					= replacing_space(truncate visio_page_normative.title, length: 45)
		.content
			= link_to page_fullscreen_path(visio_page_normative), remote: true do 
				=  replacing_space(truncate (strip_tags visio_page_normative.semantic_load), length: 305) || 'Не заполнена смысловая нагрузка'
.clearFix

/ .row-fluid style="margin-top: 20px"
/ 	div class="span2 offset2" style="min-height: 130px; background: black; background-size: cover; background-repeat: none;box-shadow: 0 0 13px #999; background-image: url('#{visio_page_normative.slides.first.image if visio_page_normative.slides.present?}');"
/ 	.span6 style="border: 2px solid #444; min-height: 130px; background: #111;"
/ 		div style="width: 100%; height: 20%; min-height: 35px; background-size: contain; background: url('/assets/bg_normative_title.png'); font-color: white"
/ 			= link_to page_fullscreen_path(visio_page_normative), remote: true do 
/  				= replacing_space(truncate visio_page_normative.title, length: 45)

app/views/pages/edit.html.slim
.well
	h1 Редактирование страницы

	== render 'form'


	h3 Добавленные свойства
	table.table
		== render @page.property
	= link_to 'Добавить свойство', new_page_property_path(@page)

	h3 Вложеные страницы
	table.table
		== render @page.children
	= link_to 'Добавить страницу', new_page_path(parent_id: @page.id )
	br

		= link_to 'Show', @page
		'|
		= link_to 'Back', pages_path

app/views/pages/form_mini.html.slim
br
br
.well
	= link_to pages_path, class: 'btn btn-inverse' do 
		i.icon-arrow-left &nbsp;
		|Назад
	br
	br

	= simple_form_for @page, html: { multipart: true } do |f|
		= f.input :parent_id, as: :hidden
		= f.input :title, placeholder: 'Наименование раздела', label: false
		= f.input :show_in_menu, label: 'Отображать в главном меню?'
		= f.input :slider, label: 'Режим слайдера?'
		= f.input :slide, as: :file, label: 'Изображение для главной'
		= f.input :color, input_html: { class: 'color' }, label: 'Цвет подсветки слайда'
		= f.input :another_color, input_html: { class: 'color' }, label: 'Вторичный цвет подсветки'

		h3 Список слайдов для слайдера
		#nested_form_slide
			= f.simple_fields_for :slides do |slide|
				== render 'slide_fields', f: slide
		= link_to_add_fields_slide "Добавить новый слайд", f, :slides
		h3 Вложеные страницы
		table.table
			== render @page.children
		= link_to new_page_path(parent_id: @page.id ), class: 'btn btn-mini btn-info' do
			i.icon-plus&nbsp;
			|Добавить страницу
		br
		br
			= f.submit 'Сохранить'

app/views/pages/index.html.slim
br
br
br
.well
  h1 Список разделов

  table.table.table-bordered
    tr
      th Название
      th

    - @pages.each do |page|
      tr
        td = page.title
        td 
          .pull-right
            = link_to 'Редактировать', edit_page_path(page), class: 'btn btn-mini btn-inverse'
            |&nbsp;|&nbsp;
            = link_to 'Удалить', page, :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-danger btn-mini'

  br

  = link_to 'Добавить раздел', new_page_path

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/pages/properties_all.html.slim
h1 Listing properties

table
  tr
    th
    th
    th

  - @properties.each do |property|
    tr
      td = link_to 'Show', property
      # td = link_to 'Destroy', property, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Property', new_property_path